version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: gradlecoding-task
    ports:
      - 8080:8080
    links:
      - mongodb
  activemq:
    image: webcenter/activemq
    container_name: activemq
    environment:
      - 'ACTIVEMQ_ADMIN_LOGIN=admin'
      - 'ACTIVEMQ_ADMIN_PASSWORD=admin'
    ports:
      - "8161:8161"